package org.wsp.models;

// Generated 14 août 2013 17:29:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AskBid generated by hbm2java
 */
@Entity
@Table(name = "AskBid", catalog = "wsp")
public class AskBid implements java.io.Serializable {

	private Integer idAskBid;
	private int turboIdTurbo;
	private int tradingSessionIdTradingSession;
	private int turboPositionIdTurboPosition;
	private int qte;
	private Date transDate;
	private String askOrBid;
	private float montantGlobal;
	private float prixUnitaire;

	public AskBid() {
	}

	public AskBid(int turboIdTurbo, int tradingSessionIdTradingSession,
			int turboPositionIdTurboPosition, int qte, Date transDate,
			String askOrBid, float montantGlobal, float prixUnitaire) {
		this.turboIdTurbo = turboIdTurbo;
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
		this.turboPositionIdTurboPosition = turboPositionIdTurboPosition;
		this.qte = qte;
		this.transDate = transDate;
		this.askOrBid = askOrBid;
		this.montantGlobal = montantGlobal;
		this.prixUnitaire = prixUnitaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAskBid", unique = true, nullable = false)
	public Integer getIdAskBid() {
		return this.idAskBid;
	}

	public void setIdAskBid(Integer idAskBid) {
		this.idAskBid = idAskBid;
	}

	@Column(name = "Turbo_idTurbo", nullable = false)
	public int getTurboIdTurbo() {
		return this.turboIdTurbo;
	}

	public void setTurboIdTurbo(int turboIdTurbo) {
		this.turboIdTurbo = turboIdTurbo;
	}

	@Column(name = "TradingSession_idTradingSession", nullable = false)
	public int getTradingSessionIdTradingSession() {
		return this.tradingSessionIdTradingSession;
	}

	public void setTradingSessionIdTradingSession(
			int tradingSessionIdTradingSession) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
	}

	@Column(name = "TurboPosition_idTurboPosition", nullable = false)
	public int getTurboPositionIdTurboPosition() {
		return this.turboPositionIdTurboPosition;
	}

	public void setTurboPositionIdTurboPosition(int turboPositionIdTurboPosition) {
		this.turboPositionIdTurboPosition = turboPositionIdTurboPosition;
	}

	@Column(name = "Qte", nullable = false)
	public int getQte() {
		return this.qte;
	}

	public void setQte(int qte) {
		this.qte = qte;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TransDate", nullable = false, length = 19)
	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

	@Column(name = "AskOrBid", nullable = false, length = 45)
	public String getAskOrBid() {
		return this.askOrBid;
	}

	public void setAskOrBid(String askOrBid) {
		this.askOrBid = askOrBid;
	}

	@Column(name = "MontantGlobal", nullable = false, precision = 12, scale = 0)
	public float getMontantGlobal() {
		return this.montantGlobal;
	}

	public void setMontantGlobal(float montantGlobal) {
		this.montantGlobal = montantGlobal;
	}

	@Column(name = "PrixUnitaire", nullable = false, precision = 12, scale = 0)
	public float getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(float prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

}
