package org.wsp.models;

// Generated 14 août 2013 17:29:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Params generated by hbm2java
 */
@Entity
@Table(name = "Params", catalog = "wsp")
public class Params implements java.io.Serializable {

	private Integer idParams;
	private String param;
	private String value;

	public Params() {
	}

	public Params(String param, String value) {
		this.param = param;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idParams", unique = true, nullable = false)
	public Integer getIdParams() {
		return this.idParams;
	}

	public void setIdParams(Integer idParams) {
		this.idParams = idParams;
	}

	@Column(name = "Param", nullable = false, length = 45)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "Value", nullable = false, length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
