package org.wsp.models;

// Generated 14 août 2013 17:29:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SuivieCapital generated by hbm2java
 */
@Entity
@Table(name = "SuivieCapital", catalog = "wsp")
public class SuivieCapital implements java.io.Serializable {

	private Integer idSuivieCapital;
	private int tradingSessionIdTradingSession;
	private int turboPositionIdTurboPosition;
	private Date snapshotTime;
	private float montant;

	public SuivieCapital() {
	}

	public SuivieCapital(int tradingSessionIdTradingSession,
			int turboPositionIdTurboPosition, Date snapshotTime, float montant) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
		this.turboPositionIdTurboPosition = turboPositionIdTurboPosition;
		this.snapshotTime = snapshotTime;
		this.montant = montant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSuivieCapital", unique = true, nullable = false)
	public Integer getIdSuivieCapital() {
		return this.idSuivieCapital;
	}

	public void setIdSuivieCapital(Integer idSuivieCapital) {
		this.idSuivieCapital = idSuivieCapital;
	}

	@Column(name = "TradingSession_idTradingSession", nullable = false)
	public int getTradingSessionIdTradingSession() {
		return this.tradingSessionIdTradingSession;
	}

	public void setTradingSessionIdTradingSession(
			int tradingSessionIdTradingSession) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
	}

	@Column(name = "TurboPosition_idTurboPosition", nullable = false)
	public int getTurboPositionIdTurboPosition() {
		return this.turboPositionIdTurboPosition;
	}

	public void setTurboPositionIdTurboPosition(int turboPositionIdTurboPosition) {
		this.turboPositionIdTurboPosition = turboPositionIdTurboPosition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SnapshotTime", nullable = false, length = 19)
	public Date getSnapshotTime() {
		return this.snapshotTime;
	}

	public void setSnapshotTime(Date snapshotTime) {
		this.snapshotTime = snapshotTime;
	}

	@Column(name = "Montant", nullable = false, precision = 12, scale = 0)
	public float getMontant() {
		return this.montant;
	}

	public void setMontant(float montant) {
		this.montant = montant;
	}

}
