package org.wsp.models;

// Generated 14 août 2013 17:29:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TradingSession generated by hbm2java
 */
@Entity
@Table(name = "TradingSession", catalog = "wsp")
public class TradingSession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5132491674278814931L;
	private Integer idTradingSession;
	private String name;
	private Date creationDate;
	private float soldeInitial;
	private float globalBalance;
	private float benefits;
	private int state;

	public TradingSession() {
	}

	public TradingSession(String name, Date creationDate, float soldeInitial,
			float globalBalance, float benefits, int state) {
		this.name = name;
		this.creationDate = creationDate;
		this.soldeInitial = soldeInitial;
		this.globalBalance = globalBalance;
		this.benefits = benefits;
		this.state = state;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTradingSession", unique = true, nullable = false)
	public Integer getIdTradingSession() {
		return this.idTradingSession;
	}

	public void setIdTradingSession(Integer idTradingSession) {
		this.idTradingSession = idTradingSession;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreationDate", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "SoldeInitial", nullable = false, precision = 12, scale = 0)
	public float getSoldeInitial() {
		return this.soldeInitial;
	}

	public void setSoldeInitial(float soldeInitial) {
		this.soldeInitial = soldeInitial;
	}

	@Column(name = "GlobalBalance", nullable = false, precision = 12, scale = 0)
	public float getGlobalBalance() {
		return this.globalBalance;
	}

	public void setGlobalBalance(float globalBalance) {
		this.globalBalance = globalBalance;
	}

	@Column(name = "Benefits", nullable = false, precision = 12, scale = 0)
	public float getBenefits() {
		return this.benefits;
	}

	public void setBenefits(float benefits) {
		this.benefits = benefits;
	}

	@Column(name = "State", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Override
	public String toString() {
		return "TradingSession [idTradingSession=" + idTradingSession
				+ ", name=" + name + ", creationDate=" + creationDate
				+ ", soldeInitial=" + soldeInitial + ", globalBalance="
				+ globalBalance + ", benefits=" + benefits + ", state=" + state
				+ "]";
	}
	
	

}
