package org.wsp.models;

// Generated 14 août 2013 17:29:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TurboPositionSimulation generated by hbm2java
 */
@Entity
@Table(name = "TurboPositionSimulation", catalog = "wsp")
public class TurboPositionSimulation implements java.io.Serializable {

	private Integer idTurboPositionSimulation;
	private int tradingSessionIdTradingSession;
	private int callIdTurbo;
	private int putIdTurbo;
	private float achatCall;
	private float venteCall;
	private float achatPut;
	private float ventePut;
	private Date creationDate;

	public TurboPositionSimulation() {
	}

	public TurboPositionSimulation(int tradingSessionIdTradingSession,
			int callIdTurbo, int putIdTurbo, float achatCall, float venteCall,
			float achatPut, float ventePut, Date creationDate) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
		this.callIdTurbo = callIdTurbo;
		this.putIdTurbo = putIdTurbo;
		this.achatCall = achatCall;
		this.venteCall = venteCall;
		this.achatPut = achatPut;
		this.ventePut = ventePut;
		this.creationDate = creationDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTurboPositionSimulation", unique = true, nullable = false)
	public Integer getIdTurboPositionSimulation() {
		return this.idTurboPositionSimulation;
	}

	public void setIdTurboPositionSimulation(Integer idTurboPositionSimulation) {
		this.idTurboPositionSimulation = idTurboPositionSimulation;
	}

	@Column(name = "TradingSession_idTradingSession", nullable = false)
	public int getTradingSessionIdTradingSession() {
		return this.tradingSessionIdTradingSession;
	}

	public void setTradingSessionIdTradingSession(
			int tradingSessionIdTradingSession) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
	}

	@Column(name = "Call_idTurbo", nullable = false)
	public int getCallIdTurbo() {
		return this.callIdTurbo;
	}

	public void setCallIdTurbo(int callIdTurbo) {
		this.callIdTurbo = callIdTurbo;
	}

	@Column(name = "Put_IdTurbo", nullable = false)
	public int getPutIdTurbo() {
		return this.putIdTurbo;
	}

	public void setPutIdTurbo(int putIdTurbo) {
		this.putIdTurbo = putIdTurbo;
	}

	@Column(name = "AchatCall", nullable = false, precision = 12, scale = 0)
	public float getAchatCall() {
		return this.achatCall;
	}

	public void setAchatCall(float achatCall) {
		this.achatCall = achatCall;
	}

	@Column(name = "VenteCall", nullable = false, precision = 12, scale = 0)
	public float getVenteCall() {
		return this.venteCall;
	}

	public void setVenteCall(float venteCall) {
		this.venteCall = venteCall;
	}

	@Column(name = "AchatPut", nullable = false, precision = 12, scale = 0)
	public float getAchatPut() {
		return this.achatPut;
	}

	public void setAchatPut(float achatPut) {
		this.achatPut = achatPut;
	}

	@Column(name = "VentePut", nullable = false, precision = 12, scale = 0)
	public float getVentePut() {
		return this.ventePut;
	}

	public void setVentePut(float ventePut) {
		this.ventePut = ventePut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreationDate", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
