package org.wsp.models;

// Generated 14 août 2013 17:29:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TurboPosition generated by hbm2java
 */
@Entity
@Table(name = "TurboPosition", catalog = "wsp")
public class TurboPosition implements java.io.Serializable {

	private Integer idTurboPosition;
	private int tradingSessionIdTradingSession;
	private int turboIdTurbo;
	private int qte;
	private float achat;
	private float vente;
	private float prixSousJacent;
	private Date creationDate;

	public TurboPosition() {
	}

	public TurboPosition(int tradingSessionIdTradingSession, int turboIdTurbo,
			int qte, float achat, float vente, float prixSousJacent,
			Date creationDate) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
		this.turboIdTurbo = turboIdTurbo;
		this.qte = qte;
		this.achat = achat;
		this.vente = vente;
		this.prixSousJacent = prixSousJacent;
		this.creationDate = creationDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTurboPosition", unique = true, nullable = false)
	public Integer getIdTurboPosition() {
		return this.idTurboPosition;
	}

	public void setIdTurboPosition(Integer idTurboPosition) {
		this.idTurboPosition = idTurboPosition;
	}

	@Column(name = "TradingSession_idTradingSession", nullable = false)
	public int getTradingSessionIdTradingSession() {
		return this.tradingSessionIdTradingSession;
	}

	public void setTradingSessionIdTradingSession(
			int tradingSessionIdTradingSession) {
		this.tradingSessionIdTradingSession = tradingSessionIdTradingSession;
	}

	@Column(name = "Turbo_idTurbo", nullable = false)
	public int getTurboIdTurbo() {
		return this.turboIdTurbo;
	}

	public void setTurboIdTurbo(int turboIdTurbo) {
		this.turboIdTurbo = turboIdTurbo;
	}

	@Column(name = "Qte", nullable = false)
	public int getQte() {
		return this.qte;
	}

	public void setQte(int qte) {
		this.qte = qte;
	}

	@Column(name = "Achat", nullable = false, precision = 12, scale = 0)
	public float getAchat() {
		return this.achat;
	}

	public void setAchat(float achat) {
		this.achat = achat;
	}

	@Column(name = "Vente", nullable = false, precision = 12, scale = 0)
	public float getVente() {
		return this.vente;
	}

	public void setVente(float vente) {
		this.vente = vente;
	}

	@Column(name = "PrixSousJacent", nullable = false, precision = 12, scale = 0)
	public float getPrixSousJacent() {
		return this.prixSousJacent;
	}

	public void setPrixSousJacent(float prixSousJacent) {
		this.prixSousJacent = prixSousJacent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreationDate", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
